### ISSUE TITLE
Wildfly 8.2.1 Could not find any attribute matching: XACommitCount

### ISSUE THREAD

**Issue by juliohm1978** [nlighten/wildfly_exporter#2]
Just tried running v0.0.2 of the module under Wildfly 8.2.1 / JDK 8 and this Exception pops up when trying to access /metrics.

```
2018-02-16 17:10:19,238 ERROR [stderr] (default task-8) javax.management.AttributeNotFoundException: JBAS011330: Could not find any attribute matching: XACommitCount
2018-02-16 17:10:19,241 ERROR [stderr] (default task-8) 	at org.jboss.as.jmx.model.ModelControllerMBeanHelper.findAttributeName(ModelControllerMBeanHelper.java:501)
2018-02-16 17:10:19,242 ERROR [stderr] (default task-8) 	at org.jboss.as.jmx.model.ModelControllerMBeanHelper.getAttribute(ModelControllerMBeanHelper.java:239)
2018-02-16 17:10:19,242 ERROR [stderr] (default task-8) 	at org.jboss.as.jmx.model.ModelControllerMBeanHelper.getAttribute(ModelControllerMBeanHelper.java:211)
2018-02-16 17:10:19,242 ERROR [stderr] (default task-8) 	at org.jboss.as.jmx.model.ModelControllerMBeanServerPlugin.getAttribute(ModelControllerMBeanServerPlugin.java:126)
2018-02-16 17:10:19,242 ERROR [stderr] (default task-8) 	at org.jboss.as.jmx.PluggableMBeanServerImpl.getAttribute(PluggableMBeanServerImpl.java:393)
2018-02-16 17:10:19,243 ERROR [stderr] (default task-8) 	at nl.nlighten.prometheus.wildfly.JbossJdbcPoolExports.collect(JbossJdbcPoolExports.java:109)
2018-02-16 17:10:19,243 ERROR [stderr] (default task-8) 	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:180)
2018-02-16 17:10:19,243 ERROR [stderr] (default task-8) 	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:213)
2018-02-16 17:10:19,243 ERROR [stderr] (default task-8) 	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:134)
2018-02-16 17:10:19,244 ERROR [stderr] (default task-8) 	at io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:22)
2018-02-16 17:10:19,244 ERROR [stderr] (default task-8) 	at io.prometheus.client.exporter.MetricsServlet.doGet(MetricsServlet.java:43)
2018-02-16 17:10:19,244 ERROR [stderr] (default task-8) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
2018-02-16 17:10:19,244 ERROR [stderr] (default task-8) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
2018-02-16 17:10:19,245 ERROR [stderr] (default task-8) 	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:86)
2018-02-16 17:10:19,245 ERROR [stderr] (default task-8) 	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
2018-02-16 17:10:19,245 ERROR [stderr] (default task-8) 	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
2018-02-16 17:10:19,245 ERROR [stderr] (default task-8) 	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
2018-02-16 17:10:19,245 ERROR [stderr] (default task-8) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
2018-02-16 17:10:19,246 ERROR [stderr] (default task-8) 	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
2018-02-16 17:10:19,246 ERROR [stderr] (default task-8) 	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
2018-02-16 17:10:19,246 ERROR [stderr] (default task-8) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
2018-02-16 17:10:19,246 ERROR [stderr] (default task-8) 	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
2018-02-16 17:10:19,247 ERROR [stderr] (default task-8) 	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
2018-02-16 17:10:19,247 ERROR [stderr] (default task-8) 	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:58)
2018-02-16 17:10:19,247 ERROR [stderr] (default task-8) 	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:70)
2018-02-16 17:10:19,247 ERROR [stderr] (default task-8) 	at io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76)
2018-02-16 17:10:19,248 ERROR [stderr] (default task-8) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
2018-02-16 17:10:19,248 ERROR [stderr] (default task-8) 	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
2018-02-16 17:10:19,248 ERROR [stderr] (default task-8) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
2018-02-16 17:10:19,248 ERROR [stderr] (default task-8) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
2018-02-16 17:10:19,249 ERROR [stderr] (default task-8) 	at io.undertow.server.handlers.MetricsHandler.handleRequest(MetricsHandler.java:62)
2018-02-16 17:10:19,249 ERROR [stderr] (default task-8) 	at io.undertow.servlet.core.MetricsChainHandler.handleRequest(MetricsChainHandler.java:59)
2018-02-16 17:10:19,249 ERROR [stderr] (default task-8) 	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:261)
2018-02-16 17:10:19,249 ERROR [stderr] (default task-8) 	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:248)
2018-02-16 17:10:19,250 ERROR [stderr] (default task-8) 	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:77)
2018-02-16 17:10:19,250 ERROR [stderr] (default task-8) 	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:167)
2018-02-16 17:10:19,250 ERROR [stderr] (default task-8) 	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:199)
2018-02-16 17:10:19,250 ERROR [stderr] (default task-8) 	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:761)
2018-02-16 17:10:19,251 ERROR [stderr] (default task-8) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2018-02-16 17:10:19,251 ERROR [stderr] (default task-8) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2018-02-16 17:10:19,251 ERROR [stderr] (default task-8) 	at java.lang.Thread.run(Thread.java:748)
2018-02-16 17:10:19,274 ERROR [io.undertow.request] (default task-8) UT005023: Exception handling request to /metrics/: java.lang.NullPointerException
	at io.prometheus.client.exporter.common.TextFormat.writeEscapedLabelValue(TextFormat.java:71) [simpleclient_common-0.0.26.jar:]
	at io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:42) [simpleclient_common-0.0.26.jar:]
	at io.prometheus.client.exporter.MetricsServlet.doGet(MetricsServlet.java:43) [simpleclient_servlet-0.0.26.jar:]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) [jboss-servlet-api_3.1_spec-1.0.0.Final.jar:1.0.0.Final]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [jboss-servlet-api_3.1_spec-1.0.0.Final.jar:1.0.0.Final]
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:86) [undertow-servlet-1.1.8.Final.jar:1.1.8.Final]
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) [undertow-servlet-1.1.8.Final.jar:1.1.8.Final]
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) [undertow-servlet-1.1.8.Final.jar:1.1.8.Final]
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.1.8.Final.jar:1.1.8.Final]
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131) [undertow-servlet-1.1.8.Final.jar:1.1.8.Final]
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) [undertow-servlet-1.1.8.Final.jar:1.1.8.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.1.8.Final.jar:1.1.8.Final]
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) [undertow-core-1.1.8.Final.jar:1.1.8.Final]
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) [undertow-servlet-1.1.8.Final.jar:1.1.8.Final]
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:58) [undertow-core-1.1.8.Final.jar:1.1.8.Final]
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:70) [undertow-servlet-1.1.8.Final.jar:1.1.8.Final]
	at io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76) [undertow-core-1.1.8.Final.jar:1.1.8.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.1.8.Final.jar:1.1.8.Final]
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.1.8.Final.jar:1.1.8.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.1.8.Final.jar:1.1.8.Final]
	at io.undertow.server.handlers.MetricsHandler.handleRequest(MetricsHandler.java:62) [undertow-core-1.1.8.Final.jar:1.1.8.Final]
	at io.undertow.servlet.core.MetricsChainHandler.handleRequest(MetricsChainHandler.java:59) [undertow-servlet-1.1.8.Final.jar:1.1.8.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:261) [undertow-servlet-1.1.8.Final.jar:1.1.8.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:248) [undertow-servlet-1.1.8.Final.jar:1.1.8.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:77) [undertow-servlet-1.1.8.Final.jar:1.1.8.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:167) [undertow-servlet-1.1.8.Final.jar:1.1.8.Final]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:199) [undertow-core-1.1.8.Final.jar:1.1.8.Final]
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:761) [undertow-core-1.1.8.Final.jar:1.1.8.Final]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [rt.jar:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [rt.jar:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) [rt.jar:1.8.0_162]
```

Any ideas?

Metrics get broken, causing an invalid list as output.

```
# HELP jvm_gc_collection_seconds Time spent in a given JVM garbage collector in seconds.
# TYPE jvm_gc_collection_seconds summary
jvm_gc_collection_seconds_count{gc="PS Scavenge",} 6.0
jvm_gc_collection_seconds_sum{gc="PS Scavenge",} 0.114
jvm_gc_collection_seconds_count{gc="PS MarkSweep",} 3.0
jvm_gc_collection_seconds_sum{gc="PS MarkSweep",} 0.222
# HELP jvm_info JVM version info
# TYPE jvm_info gauge
jvm_info{version="1.8.0_162-b12",vendor="Oracle Corporation",} 1.0
# HELP jvm_classes_loaded The number of classes that are currently loaded in the JVM
# TYPE jvm_classes_loaded gauge
jvm_classes_loaded 10887.0
# HELP jvm_classes_loaded_total The total number of classes that have been loaded since the JVM has started execution
# TYPE jvm_classes_loaded_total counter
jvm_classes_loaded_total 10887.0
# HELP jvm_classes_unloaded_total The total number of classes that have been unloaded since the JVM has started execution
# TYPE jvm_classes_unloaded_total counter
jvm_classes_unloaded_total 0.0
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 14.41
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.518808175132E9
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 537.0
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1048576.0
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 7.974301696E9
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 4.56810496E8
# HELP jvm_threads_current Current thread count of a JVM
# TYPE jvm_threads_current gauge
jvm_threads_current 112.0
# HELP jvm_threads_daemon Daemon thread count of a JVM
# TYPE jvm_threads_daemon gauge
jvm_threads_daemon 24.0
# HELP jvm_threads_peak Peak thread count of a JVM
# TYPE jvm_threads_peak gauge
jvm_threads_peak 160.0
# HELP jvm_threads_started_total Started thread count of a JVM
# TYPE jvm_threads_started_total counter
jvm_threads_started_total 177.0
# HELP jvm_threads_deadlocked Cycles of JVM-threads that are in deadlock waiting to acquire object monitors or ownable synchronizers
# TYPE jvm_threads_deadlocked gauge
jvm_threads_deadlocked 0.0
# HELP jvm_threads_deadlocked_monitor Cycles of JVM-threads that are in deadlock waiting to acquire object monitors
# TYPE jvm_threads_deadlocked_monitor gauge
jvm_threads_deadlocked_monitor 0.0
# HELP wildfly_info Wildfly version info
# TYPE wildfly_info gauge
wildfly_info{name="
```

**Comment by rswart** [comment]
Apologies for my late response. I completely missed this post.

Apparently the XACommitCount attribute is not available. Did you configure a non-XA datasource? If so, could you try the same scenario with an XA datasource just to validate the error disappears? If this is the case I am willing to look into supporting non-XA datasources. If not, it is probably related to Wildfly 8.2 which is too old for me to start supporting.

**Comment by juliohm1978** [comment]
Yes, we have non-XA datasources, but we are no longer using this exporter in favor of the official [prometheus/jmx_exporter](https://github.com/prometheus/jmx_exporter). Will gladly reopen in the future if we stumble into this issue again.

Thank you for the response, regardless!
